require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Rails/Output:
  Exclude:
    - db/seeds.rb

RSpec/MultipleMemoizedHelpers:
  # default: 5
  Max: 10

Style/Documentation:
  Enabled: false
