name: Linters

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Install RuboCop
        run: gem install rubocop rubocop-performance rubocop-rails rubocop-rspec
      - name: Run RuboCop
        run: rubocop
